import { Work_Sans } from 'next/font/google'
import './globals.scss'

const workS = Work_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'ECO-site',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={workS.className}>{children}</body>
    </html>
  )
}
